version: 2
updates:
  - package-ecosystem: npm
    directory: /back
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /front/disciplina-front
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
