version: 2

updates:
  - package-ecosystem: npm
    directory: /back
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 20
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: /front/disciplina-front
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 20
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
