version: '3.9'

services:
  sql-db:
    image: mysql:8.4.8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=listing
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./database/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql/mysql-data:/var/lib/mysql
    networks:
      - back-end
  nosql-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database/mongodb/mongodb-data:/data/db
      - ./database/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - back-end
networks:
  front-end:
  back-end: