version: '3.9'

services:
  sql-db:
    image: mysql:8.4.8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql/mysql-data:/var/lib/mysql
    networks:
      - back-end
    ports:
      - 5001:3306
  nosql-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database/mongodb/mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:27017
  backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./back/.env
    networks:
      - back-end
      - front-end
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./front/disciplina-front
      dockerfile: Dockerfile
    networks:
      - front-end
    ports:
      - "5173:5173"
networks:
  front-end:
  back-end: