import gql from 'graphql-tag';

export const typeDefs = gql`
    enum AlternantSequenceStatus {
        pending
        done
        not_done
    }

    type AlternantCompany {
        name: String
        address: String
        mentorName: String
        startDate: String
        endDate: String
    }

    type Alternant {
        id: ID!
        firstName: String!
        lastName: String!
        fullName: String!
        session: String!
        sessionId: String
        email: String
        phone: String
        candidateId: String
        company: AlternantCompany
        linkedAlternantIds: [String!]!
        archived: Boolean!
        archivedAt: String
        createdAt: String
        updatedAt: String
    }

    type Session {
        id: ID!
        nom: String!
        filiere: String
        jourCours: String
        dateDebut: String!
        dateFin: String!
        alternantCount: Int!
        createdAt: String
        updatedAt: String
    }

    type AlternantSequenceContacts {
        mentor: Boolean!
        alternant: Boolean!
        formateur: Boolean!
    }

    type AlternantSequence {
        id: ID!
        alternantId: ID!
        numero: Int!
        prevueLe: String!
        status: AlternantSequenceStatus!
        realiseeLe: String
        contacts: AlternantSequenceContacts!
        contactsDone: Int!
        autoGenerated: Boolean!
        archived: Boolean!
        archivedAt: String
        createdAt: String
        updatedAt: String
    }

    input AlternantCompanyInput {
        name: String
        address: String
        mentorName: String
        startDate: String!
        endDate: String
    }

    input CreateAlternantInput {
        firstName: String!
        lastName: String!
        session: String!
        sessionId: String
        email: String
        phone: String
        candidateId: String
        company: AlternantCompanyInput!
        linkedAlternantIds: [String!]
    }

    input UpdateAlternantInput {
        firstName: String
        lastName: String
        session: String
        sessionId: String
        email: String
        phone: String
        candidateId: String
    }

    input CreateSessionInput {
        nom: String!
        filiere: String
        jourCours: String
        dateDebut: String!
        dateFin: String!
    }

    input UpdateSessionInput {
        nom: String
        filiere: String
        jourCours: String
        dateDebut: String
        dateFin: String
    }

    input AlternantSequenceContactsInput {
        mentor: Boolean
        alternant: Boolean
        formateur: Boolean
    }

    type AlternantEmailCheck {
        exists: Boolean!
        id: String
        fullName: String
    }

    type Rupture {
        id: ID!
        alternantId: ID!
        firstName: String
        lastName: String
        fullName: String!
        session: String!
        sessionId: String
        dateRupture: String!
        entreprise: String
        motif: String!
        detail: String
        poursuitFormation: Boolean!
        createdAt: String
        updatedAt: String
    }

    input DeclareRuptureInput {
        alternantId: ID!
        dateRupture: String!
        entreprise: String
        motif: String!
        detail: String
        poursuitFormation: Boolean!
    }

    input UpdateRuptureInput {
        dateRupture: String
        entreprise: String
        motif: String
        detail: String
        poursuitFormation: Boolean
    }

    type Query {
        alternants(search: String, includeArchived: Boolean): [Alternant!]!
        alternant(id: ID!): Alternant
        alternantSequences(alternantId: ID!): [AlternantSequence!]!
        alternantByEmail(email: String!): AlternantEmailCheck!
        sessions(search: String): [Session!]!
        session(id: ID!): Session
        sessionAlternants(sessionId: ID!): [Alternant!]!
        ruptures(year: Int!, month: Int!): [Rupture!]!
        alternantRuptures(alternantId: ID!): [Rupture!]!
    }

    type Mutation {
        createAlternant(input: CreateAlternantInput!): Alternant!
        updateAlternant(id: ID!, input: UpdateAlternantInput!): Alternant
        deleteAlternant(id: ID!): Boolean!
        changeAlternantCompany(id: ID!, company: AlternantCompanyInput!): Alternant
        removeAlternantCompany(id: ID!): Alternant
        linkAlternant(id: ID!, otherId: ID!): Alternant
        unlinkAlternant(id: ID!, otherId: ID!): Alternant
        archiveAlternant(id: ID!): Alternant
        unarchiveAlternant(id: ID!): Alternant
        createSequence(alternantId: ID!, prevueLe: String!): AlternantSequence!
        updateSequenceContacts(id: ID!, contacts: AlternantSequenceContactsInput!): AlternantSequence
        completeSequence(id: ID!, realiseeLe: String!): AlternantSequence
        markSequence(id: ID!, status: AlternantSequenceStatus!): AlternantSequence
        deleteSequence(id: ID!): Boolean!
        createSession(input: CreateSessionInput!): Session!
        updateSession(id: ID!, input: UpdateSessionInput!): Session
        deleteSession(id: ID!): Boolean!
        assignAlternantToSession(sessionId: ID!, alternantId: ID!): Session
        removeAlternantFromSession(sessionId: ID!, alternantId: ID!): Session
        declareRupture(input: DeclareRuptureInput!): Rupture!
        updateRupture(id: ID!, input: UpdateRuptureInput!): Rupture
        deleteRupture(id: ID!): Boolean!
    }
`;
