import gql from 'graphql-tag';

export const typeDefs = gql`
    enum AlternantSequenceStatus {
        pending
        done
        not_done
    }

    type AlternantCompany {
        name: String
        address: String
        mentorName: String
        startDate: String
        endDate: String
    }

    type Alternant {
        id: ID!
        firstName: String!
        lastName: String!
        fullName: String!
        session: String!
        email: String
        phone: String
        candidateId: String
        company: AlternantCompany
        linkedAlternantIds: [String!]!
        createdAt: String
        updatedAt: String
    }

    type AlternantSequenceContacts {
        mentor: Boolean!
        alternant: Boolean!
        formateur: Boolean!
    }

    type AlternantSequence {
        id: ID!
        alternantId: ID!
        numero: Int!
        prevueLe: String!
        status: AlternantSequenceStatus!
        realiseeLe: String
        contacts: AlternantSequenceContacts!
        contactsDone: Int!
        autoGenerated: Boolean!
        createdAt: String
        updatedAt: String
    }

    input AlternantCompanyInput {
        name: String
        address: String
        mentorName: String
        startDate: String!
        endDate: String
    }

    input CreateAlternantInput {
        firstName: String!
        lastName: String!
        session: String!
        email: String
        phone: String
        candidateId: String
        company: AlternantCompanyInput!
        linkedAlternantIds: [String!]
    }

    input UpdateAlternantInput {
        firstName: String
        lastName: String
        session: String
        email: String
        phone: String
        candidateId: String
    }

    input AlternantSequenceContactsInput {
        mentor: Boolean
        alternant: Boolean
        formateur: Boolean
    }

    type AlternantEmailCheck {
        exists: Boolean!
        id: String
        fullName: String
    }

    type Query {
        alternants(search: String): [Alternant!]!
        alternant(id: ID!): Alternant
        alternantSequences(alternantId: ID!): [AlternantSequence!]!
        alternantByEmail(email: String!): AlternantEmailCheck!
    }

    type Mutation {
        createAlternant(input: CreateAlternantInput!): Alternant!
        updateAlternant(id: ID!, input: UpdateAlternantInput!): Alternant
        deleteAlternant(id: ID!): Boolean!
        changeAlternantCompany(id: ID!, company: AlternantCompanyInput!): Alternant
        removeAlternantCompany(id: ID!): Alternant
        linkAlternant(id: ID!, otherId: ID!): Alternant
        unlinkAlternant(id: ID!, otherId: ID!): Alternant
        createSequence(alternantId: ID!, prevueLe: String!): AlternantSequence!
        updateSequenceContacts(id: ID!, contacts: AlternantSequenceContactsInput!): AlternantSequence
        completeSequence(id: ID!, realiseeLe: String!): AlternantSequence
        markSequence(id: ID!, status: AlternantSequenceStatus!): AlternantSequence
        deleteSequence(id: ID!): Boolean!
    }
`;
