export enum JobStatus {
  NOT_MATCHED = 'NOT_MATCHED',
  MATCHED = 'MATCHED',
  ZERO_MATCHED = 'ZERO_MATCHED',
  CV_SEND = 'CV_SEND',
  IMMERSING = 'IMMERSING',
  CONTRACT = 'CONTRACT',
}

export enum DesiredTP {
  AD = 'AD',
  CC = 'CC',
  NTC = 'NTC',
  REM = 'REM',
  SA = 'SA',
}

export enum DesiredSex {
  MIXTE = 'MIXTE',
  FILLE = 'FILLE',
  GARCON = 'GARCON',
}

export enum Sector {
  BOULANGERIE = 'BOULANGERIE',
  RESTAURATION = 'RESTAURATION',
  STATION = 'STATION',
  PAP = 'PAP',
  LIBRE_SERVICE = 'LIBRE_SERVICE',
  TELEPHONIE = 'TELEPHONIE',
  AUTO = 'AUTO',
  COMMERCIAL = 'COMMERCIAL',
  BIJOUX = 'BIJOUX',
  COSMETIQUE = 'COSMETIQUE',
  IMMOBILIER = 'IMMOBILIER',
  ASSURANCE = 'ASSURANCE',
  ANIMAUX = 'ANIMAUX',
  SPORT = 'SPORT',
  ENFANT = 'ENFANT',
  PHARMACIE = 'PHARMACIE',
  BAZAR = 'BAZAR',
  NONE = 'NONE',
}

export enum Localisation {
  SAINT_DENIS = 'SAINT_DENIS',
  SAINTE_MARIE = 'SAINTE_MARIE',
  SAINTE_SUZANNE = 'SAINTE_SUZANNE',
  SAINT_PAUL = 'SAINT_PAUL',
  LA_POSSESSION = 'LA_POSSESSION',
  LE_PORT = 'LE_PORT',
  TROIS_BASSINS = 'TROIS_BASSINS',
  SAINT_LEU = 'SAINT_LEU',
  SAINT_PIERRE = 'SAINT_PIERRE',
  CILAOS = 'CILAOS',
  ETANG_SALE = 'ETANG_SALE',
  SAINT_LOUIS = 'SAINT_LOUIS',
  ENTRE_DEUX = 'ENTRE_DEUX',
  LES_AVIRONS = 'LES_AVIRONS',
  LE_TAMPON = 'LE_TAMPON',
  SAINT_PHILLIPE = 'SAINT_PHILLIPE',
  SAINT_JOSEPH = 'SAINT_JOSEPH',
  PETIT_ILE = 'PETIT_ILE',
  SAINTE_ROSE = 'SAINTE_ROSE',
  SAINT_BENOIT = 'SAINT_BENOIT',
  BRAS_PANON = 'BRAS_PANON',
  SAINT_ANDRE = 'SAINT_ANDRE',
  LA_PLAINE_DES_PALMISTES = 'LA_PLAINE_DES_PALMISTES',
  SALAZIE = 'SALAZIE',
  SAINTE_ANNE = 'SAINTE_ANNE',
}

export const formatEnumLabel = (value: string): string => {
  return value
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
}
