services:
  changedetection:
    image: dgtlmoon/changedetection.io
    container_name: changedetection
    volumes:
      - changedetection-data:/datastore
    ports:
      - "127.0.0.1:5000:5000"
    restart: no

volumes:
  changedetection-data: