CREATE TABLE IF NOT EXISTS `company_conflict` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `ab_id` varchar(36) DEFAULT NULL,
  `legal_referent` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `sector` varchar(255) DEFAULT NULL,
  `main_activity` varchar(255) DEFAULT NULL,
  `siret` char(14) DEFAULT NULL,
  `idcc` char(4) DEFAULT NULL,
  `ape` char(5) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `conclusion` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `relance_date` date DEFAULT NULL,
  `relance_type` tinyint DEFAULT NULL,
  `relance_template_id` varchar(64) DEFAULT NULL,
  `relance_channel` enum('PHONE','MAIL') DEFAULT NULL,
  `candidate_user_ids` text DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_company_conflict_siret` (`siret`),
  CONSTRAINT `fk_company_conflict_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
