import { describe, it, expect } from 'vitest';
import { mintAuthCookies } from '../../../../test/helpers/auth';
import { env } from '../../../config/env';

const ENDPOINT = `http://localhost:${env.API_PORT}/api/graphql/peda`;

function pedaAuth() {
    return mintAuthCookies({ id: 1, email: 'peda@test.local', role: 'PEDA', permission: 'EMPLOYEE' });
}

function gqlFetch(auth: { cookieHeader: string; csrfHeader: string }, query: string, variables?: unknown) {
    return fetch(ENDPOINT, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Cookie: auth.cookieHeader,
            'x-csrf-token': auth.csrfHeader,
        },
        body: JSON.stringify({ query, variables }),
    }).then((res) => res.json());
}

const CREATE = `
    mutation($input: CreateAlternantInput!) {
        createAlternant(input: $input) {
            id firstName lastName fullName session email phone
            company { name address mentorName startDate endDate }
            linkedAlternantIds
        }
    }
`;

function createInput(suffix: string | number, overrides: Record<string, unknown> = {}) {
    return {
        firstName: `Léa-${suffix}`,
        lastName: `Martin-${suffix}`,
        session: `SIO-${suffix}`,
        email: `lea-${suffix}@test.local`,
        phone: '0692000000',
        company: {
            name: 'Acme SARL',
            address: '12 rue des Palmiers, Saint-Denis',
            mentorName: 'Jean Dupont',
            startDate: '2026-09-01',
            endDate: '2027-06-30',
        },
        ...overrides,
    };
}

describe('GraphQL peda alternants', () => {
    it('creates an alternant and auto-generates the SA schedule (J+15, 10 weeks, +4 months)', async () => {
        const auth = pedaAuth();
        const suffix = Date.now();
        const created = await gqlFetch(auth, CREATE, { input: createInput(suffix) });
        expect(created.errors).toBeUndefined();
        const alternant = created.data.createAlternant;
        expect(alternant.fullName).toBe(`Léa-${suffix} Martin-${suffix}`);
        expect(alternant.company.name).toBe('Acme SARL');

        const seqs = await gqlFetch(
            auth,
            `query($alternantId: ID!) {
                alternantSequences(alternantId: $alternantId) { numero prevueLe status autoGenerated contactsDone }
            }`,
            { alternantId: alternant.id },
        );
        expect(seqs.errors).toBeUndefined();
        const list = seqs.data.alternantSequences;
        // 2026-09-01 +15j = 09-16, +70j = 11-10, +4 mois = 2027-03-10 (<= fin 06-30), +4 mois = 07-10 (hors fin).
        expect(list.map((s: { numero: number }) => s.numero)).toEqual([1, 2, 3]);
        expect(list.map((s: { prevueLe: string }) => s.prevueLe.slice(0, 10))).toEqual([
            '2026-09-16',
            '2026-11-10',
            '2027-03-10',
        ]);
        expect(list.every((s: { autoGenerated: boolean }) => s.autoGenerated)).toBe(true);
    });

    it('rejects creation without required fields', async () => {
        const auth = pedaAuth();
        const res = await gqlFetch(auth, CREATE, {
            input: createInput(Date.now(), { firstName: '  ', session: '' }),
        });
        expect(res.errors).toBeDefined();
        expect(res.data).toBeNull();
    });

    it('rejects creation and update with a duplicate email', async () => {
        const auth = pedaAuth();
        const suffix = Date.now();
        const email = `dup-${suffix}@test.local`;
        const first = await gqlFetch(auth, CREATE, { input: createInput(`${suffix}a`, { email }) });
        expect(first.errors).toBeUndefined();

        const dup = await gqlFetch(auth, CREATE, {
            input: createInput(`${suffix}b`, { email: email.toUpperCase() }),
        });
        expect(dup.errors).toBeDefined();
        expect(String(dup.errors[0].message)).toMatch(/déjà avec cet email/);

        const second = (
            await gqlFetch(auth, CREATE, { input: createInput(`${suffix}c`, { email: `autre-${suffix}@test.local` }) })
        ).data.createAlternant;
        const conflict = await gqlFetch(
            auth,
            `mutation($id: ID!, $input: UpdateAlternantInput!) {
                updateAlternant(id: $id, input: $input) { id }
            }`,
            { id: second.id, input: { email } },
        );
        expect(conflict.errors).toBeDefined();
    });

    it('checks email duplicates via alternantByEmail', async () => {
        const auth = pedaAuth();
        const suffix = Date.now();
        const email = `lookup-${suffix}@test.local`;
        const created = (await gqlFetch(auth, CREATE, { input: createInput(suffix, { email }) })).data.createAlternant;

        const hit = await gqlFetch(
            auth,
            `query($email: String!) { alternantByEmail(email: $email) { exists id fullName } }`,
            {
                email,
            },
        );
        expect(hit.errors).toBeUndefined();
        expect(hit.data.alternantByEmail).toMatchObject({ exists: true, id: created.id });

        const miss = await gqlFetch(auth, `query($email: String!) { alternantByEmail(email: $email) { exists id } }`, {
            email: `inconnu-${suffix}@test.local`,
        });
        expect(miss.data.alternantByEmail.exists).toBe(false);
        expect(miss.data.alternantByEmail.id).toBeNull();
    });

    it('links alternants symmetrically and unlinks them', async () => {
        const auth = pedaAuth();
        const suffix = Date.now();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(`${suffix}a`) })).data.createAlternant;
        const b = (await gqlFetch(auth, CREATE, { input: createInput(`${suffix}b`) })).data.createAlternant;

        const linked = await gqlFetch(
            auth,
            `mutation($id: ID!, $otherId: ID!) { linkAlternant(id: $id, otherId: $otherId) { id linkedAlternantIds } }`,
            { id: a.id, otherId: b.id },
        );
        expect(linked.errors).toBeUndefined();
        expect(linked.data.linkAlternant.linkedAlternantIds).toEqual([b.id]);

        const fetched = await gqlFetch(auth, `query($id: ID!) { alternant(id: $id) { linkedAlternantIds } }`, {
            id: b.id,
        });
        expect(fetched.data.alternant.linkedAlternantIds).toEqual([a.id]);

        const unlinked = await gqlFetch(
            auth,
            `mutation($id: ID!, $otherId: ID!) { unlinkAlternant(id: $id, otherId: $otherId) { linkedAlternantIds } }`,
            { id: a.id, otherId: b.id },
        );
        expect(unlinked.data.unlinkAlternant.linkedAlternantIds).toEqual([]);
    });

    it('ticks 3/3 contacts without completing, then validates with a date and reschedules later SAs', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;

        const list = await gqlFetch(
            auth,
            `query($alternantId: ID!) {
                alternantSequences(alternantId: $alternantId) { id numero prevueLe status }
            }`,
            { alternantId: a.id },
        );
        // Planning auto : 09-16 (n°1), 11-10 (n°2), 2027-03-10 (n°3).
        const first = list.data.alternantSequences.find((s: { numero: number }) => s.numero === 1);
        expect(first.prevueLe.slice(0, 10)).toBe('2026-09-16');

        const contacts = await gqlFetch(
            auth,
            `mutation($id: ID!, $contacts: AlternantSequenceContactsInput!) {
                updateSequenceContacts(id: $id, contacts: $contacts) {
                    status realiseeLe contactsDone
                }
            }`,
            { id: first.id, contacts: { mentor: true, alternant: true, formateur: true } },
        );
        expect(contacts.errors).toBeUndefined();
        expect(contacts.data.updateSequenceContacts.contactsDone).toBe(3);
        // Cocher les 3 ne valide PAS la SA — elle reste en attente.
        expect(contacts.data.updateSequenceContacts.status).toBe('pending');
        expect(contacts.data.updateSequenceContacts.realiseeLe).toBeNull();

        // Validation avec date de réalisation : +4 jours → SA suivantes décalées de +4 jours.
        const completed = await gqlFetch(
            auth,
            `mutation($id: ID!, $realiseeLe: String!) {
                completeSequence(id: $id, realiseeLe: $realiseeLe) { status realiseeLe }
            }`,
            { id: first.id, realiseeLe: '2026-09-20' },
        );
        expect(completed.errors).toBeUndefined();
        expect(completed.data.completeSequence.status).toBe('done');
        expect(completed.data.completeSequence.realiseeLe.slice(0, 10)).toBe('2026-09-20');

        const after = await gqlFetch(
            auth,
            `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { numero prevueLe } }`,
            { alternantId: a.id },
        );
        const byNumero = Object.fromEntries(
            after.data.alternantSequences.map((s: { numero: number; prevueLe: string }) => [s.numero, s.prevueLe]),
        );
        expect(byNumero[2].slice(0, 10)).toBe('2026-11-14');
        expect(byNumero[3].slice(0, 10)).toBe('2027-03-14');
    });

    it('creates a manual sequence with the next numero', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;

        const manual = await gqlFetch(
            auth,
            `mutation($alternantId: ID!, $prevueLe: String!) {
                createSequence(alternantId: $alternantId, prevueLe: $prevueLe) { id numero prevueLe status contactsDone }
            }`,
            { alternantId: a.id, prevueLe: '2026-10-05' },
        );
        expect(manual.errors).toBeUndefined();
        // 3 SA auto (numeros 1-3) → la manuelle porte le numero 4.
        expect(manual.data.createSequence.numero).toBe(4);
        expect(manual.data.createSequence.prevueLe.slice(0, 10)).toBe('2026-10-05');
    });

    it('unchecking a contact on a completed sequence reverts it to pending', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;
        const list = await gqlFetch(
            auth,
            `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { id numero } }`,
            { alternantId: a.id },
        );
        const firstId = list.data.alternantSequences.find((s: { numero: number }) => s.numero === 1).id;
        await gqlFetch(
            auth,
            `mutation($id: ID!, $contacts: AlternantSequenceContactsInput!) {
                updateSequenceContacts(id: $id, contacts: $contacts) { contactsDone }
            }`,
            { id: firstId, contacts: { mentor: true, alternant: true, formateur: true } },
        );
        await gqlFetch(auth, `mutation($id: ID!) { completeSequence(id: $id, realiseeLe: "2026-09-20") { status } }`, {
            id: firstId,
        });
        const reverted = await gqlFetch(
            auth,
            `mutation($id: ID!, $contacts: AlternantSequenceContactsInput!) {
                updateSequenceContacts(id: $id, contacts: $contacts) { status realiseeLe contactsDone }
            }`,
            { id: firstId, contacts: { mentor: false } },
        );
        expect(reverted.errors).toBeUndefined();
        expect(reverted.data.updateSequenceContacts.status).toBe('pending');
        expect(reverted.data.updateSequenceContacts.realiseeLe).toBeNull();
        expect(reverted.data.updateSequenceContacts.contactsDone).toBe(2);
    });

    it('rejects completion without 3/3 contacts', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;
        const seqs = (
            await gqlFetch(auth, `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { id } }`, {
                alternantId: a.id,
            })
        ).data.alternantSequences;
        const res = await gqlFetch(
            auth,
            `mutation($id: ID!) { completeSequence(id: $id, realiseeLe: "2026-10-10") { status } }`,
            { id: seqs[0].id },
        );
        expect(res.errors).toBeDefined();
    });

    it('marks a sequence as not done', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;
        const seqs = (
            await gqlFetch(auth, `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { id } }`, {
                alternantId: a.id,
            })
        ).data.alternantSequences;
        const marked = await gqlFetch(
            auth,
            `mutation($id: ID!) { markSequence(id: $id, status: not_done) { status } }`,
            {
                id: seqs[0].id,
            },
        );
        expect(marked.errors).toBeUndefined();
        expect(marked.data.markSequence.status).toBe('not_done');
    });

    it('removes the company and deletes all sequences (plus d\u2019entreprise)', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;

        const removed = await gqlFetch(
            auth,
            `mutation($id: ID!) { removeAlternantCompany(id: $id) { id company { name } } }`,
            {
                id: a.id,
            },
        );
        expect(removed.errors).toBeUndefined();
        expect(removed.data.removeAlternantCompany.company).toBeNull();

        const seqs = await gqlFetch(
            auth,
            `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { id } }`,
            { alternantId: a.id },
        );
        expect(seqs.data.alternantSequences).toEqual([]);
    });

    it('changes the company and regenerates upcoming auto sequences', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;

        const changed = await gqlFetch(
            auth,
            `mutation($id: ID!, $company: AlternantCompanyInput!) {
                changeAlternantCompany(id: $id, company: $company) { id company { name startDate endDate } }
            }`,
            {
                id: a.id,
                company: { name: 'Beta SAS', startDate: '2026-10-01', endDate: '2026-11-30' },
            },
        );
        expect(changed.errors).toBeUndefined();
        expect(changed.data.changeAlternantCompany.company.name).toBe('Beta SAS');

        const seqs = await gqlFetch(
            auth,
            `query($alternantId: ID!) { alternantSequences(alternantId: $alternantId) { numero prevueLe autoGenerated } }`,
            { alternantId: a.id },
        );
        // Ancien planning auto supprimé, nouveau : J+15 = 10-16, +70j = 12-10 (> fin 11-30) → 1 seule SA.
        expect(seqs.data.alternantSequences.map((s: { prevueLe: string }) => s.prevueLe.slice(0, 10))).toEqual([
            '2026-10-16',
        ]);
    });

    it('deletes the alternant and its sequences', async () => {
        const auth = pedaAuth();
        const a = (await gqlFetch(auth, CREATE, { input: createInput(Date.now()) })).data.createAlternant;
        const deleted = await gqlFetch(auth, `mutation($id: ID!) { deleteAlternant(id: $id) }`, { id: a.id });
        expect(deleted.data.deleteAlternant).toBe(true);
        const fetched = await gqlFetch(auth, `query($id: ID!) { alternant(id: $id) { id } }`, { id: a.id });
        expect(fetched.data.alternant).toBeNull();
    });

    it('authorises the PEDA role but forbids other employee roles without permission', async () => {
        const pedaGuest = mintAuthCookies({ id: 2, email: 'peda-guest@test.local', role: 'PEDA', permission: 'GUEST' });
        const res = await gqlFetch(pedaGuest, `{ alternants { id } }`);
        expect(res.errors).toBeUndefined();

        const commercial = mintAuthCookies({ id: 3, email: 'com@test.local', role: 'COMMERCIAL', permission: 'GUEST' });
        const forbidden = await gqlFetch(commercial, `{ alternants { id } }`);
        expect(forbidden.errors).toBeDefined();
        expect(String(forbidden.errors[0].message)).toMatch(/Forbidden/);
    });
});
