import { gql } from 'urql'
import { pedaGraphqlClient, candidateGraphqlClient } from '@/graphql/client'
import { CHECK_CANDIDATE_EMAIL, GET_CANDIDATE_BY_ID } from '@/graphql/queries'
import type { Alternant, AlternantSequence, CreateAlternantInput, SequenceContacts, SequenceStatus } from '@/types/alternant'

const ALTERNANT_FIELDS = gql`
  fragment AlternantFields on Alternant {
    id
    firstName
    lastName
    fullName
    session
    email
    phone
    candidateId
    company {
      name
      address
      mentorName
      startDate
      endDate
    }
    linkedAlternantIds
    createdAt
    updatedAt
  }
`

const SEQUENCE_FIELDS = gql`
  fragment SequenceFields on AlternantSequence {
    id
    alternantId
    numero
    prevueLe
    status
    realiseeLe
    contacts {
      mentor
      alternant
      formateur
    }
    contactsDone
    autoGenerated
    createdAt
    updatedAt
  }
`

const LIST_ALTERNANTS = gql`
  query ListAlternants($search: String) {
    alternants(search: $search) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const GET_ALTERNANT = gql`
  query GetAlternant($id: ID!) {
    alternant(id: $id) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const GET_SEQUENCES = gql`
  query GetAlternantSequences($alternantId: ID!) {
    alternantSequences(alternantId: $alternantId) {
      ...SequenceFields
    }
  }
  ${SEQUENCE_FIELDS}
`

const CREATE_ALTERNANT = gql`
  mutation CreateAlternant($input: CreateAlternantInput!) {
    createAlternant(input: $input) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const UPDATE_ALTERNANT = gql`
  mutation UpdateAlternant($id: ID!, $input: UpdateAlternantInput!) {
    updateAlternant(id: $id, input: $input) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const CHECK_ALTERNANT_EMAIL = gql`
  query AlternantByEmail($email: String!) {
    alternantByEmail(email: $email) {
      exists
      id
      fullName
    }
  }
`

const DELETE_ALTERNANT = gql`
  mutation DeleteAlternant($id: ID!) {
    deleteAlternant(id: $id)
  }
`

const CHANGE_COMPANY = gql`
  mutation ChangeAlternantCompany($id: ID!, $company: AlternantCompanyInput!) {
    changeAlternantCompany(id: $id, company: $company) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const REMOVE_COMPANY = gql`
  mutation RemoveAlternantCompany($id: ID!) {
    removeAlternantCompany(id: $id) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const LINK_ALTERNANT = gql`
  mutation LinkAlternant($id: ID!, $otherId: ID!) {
    linkAlternant(id: $id, otherId: $otherId) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const UNLINK_ALTERNANT = gql`
  mutation UnlinkAlternant($id: ID!, $otherId: ID!) {
    unlinkAlternant(id: $id, otherId: $otherId) {
      ...AlternantFields
    }
  }
  ${ALTERNANT_FIELDS}
`

const CREATE_SEQUENCE = gql`
  mutation CreateSequence($alternantId: ID!, $prevueLe: String!) {
    createSequence(alternantId: $alternantId, prevueLe: $prevueLe) {
      ...SequenceFields
    }
  }
  ${SEQUENCE_FIELDS}
`

const UPDATE_CONTACTS = gql`
  mutation UpdateSequenceContacts($id: ID!, $contacts: AlternantSequenceContactsInput!) {
    updateSequenceContacts(id: $id, contacts: $contacts) {
      ...SequenceFields
    }
  }
  ${SEQUENCE_FIELDS}
`

const MARK_SEQUENCE = gql`
  mutation MarkSequence($id: ID!, $status: AlternantSequenceStatus!) {
    markSequence(id: $id, status: $status) {
      ...SequenceFields
    }
  }
  ${SEQUENCE_FIELDS}
`

const COMPLETE_SEQUENCE = gql`
  mutation CompleteSequence($id: ID!, $realiseeLe: String!) {
    completeSequence(id: $id, realiseeLe: $realiseeLe) {
      ...SequenceFields
    }
  }
  ${SEQUENCE_FIELDS}
`

const DELETE_SEQUENCE = gql`
  mutation DeleteSequence($id: ID!) {
    deleteSequence(id: $id)
  }
`

function unwrap<T>(res: { error?: { message: string }; data?: T }): T {
  if (res.error) throw new Error(res.error.message.replace(/^\[GraphQL\]\s*/, ''))
  return res.data as T
}

export async function fetchAlternants(search?: string): Promise<Alternant[]> {
  const res = await pedaGraphqlClient.query(LIST_ALTERNANTS, { search: search?.trim() || undefined }, { requestPolicy: 'network-only' })
  const data = unwrap<{ alternants: Alternant[] }>(res)
  return data.alternants
}

export async function fetchAlternant(id: string): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.query(GET_ALTERNANT, { id }, { requestPolicy: 'network-only' })
  return unwrap<{ alternant: Alternant | null }>(res).alternant
}

export async function fetchSequences(alternantId: string): Promise<AlternantSequence[]> {
  const res = await pedaGraphqlClient.query(GET_SEQUENCES, { alternantId }, { requestPolicy: 'network-only' })
  return unwrap<{ alternantSequences: AlternantSequence[] }>(res).alternantSequences
}

export async function createAlternant(input: CreateAlternantInput): Promise<Alternant> {
  const res = await pedaGraphqlClient.mutation(CREATE_ALTERNANT, { input })
  return unwrap<{ createAlternant: Alternant }>(res).createAlternant
}

export async function updateAlternant(
  id: string,
  input: { firstName?: string; lastName?: string; session?: string; email?: string | null; phone?: string | null },
): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.mutation(UPDATE_ALTERNANT, { id, input })
  return unwrap<{ updateAlternant: Alternant | null }>(res).updateAlternant
}

export interface AlternantEmailCheck {
  exists: boolean
  id: string | null
  fullName: string | null
}

export async function checkAlternantEmail(email: string): Promise<AlternantEmailCheck | null> {
  const trimmed = email.trim()
  if (!trimmed || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) return null
  const res = await pedaGraphqlClient.query(CHECK_ALTERNANT_EMAIL, { email: trimmed }, { requestPolicy: 'network-only' })
  return unwrap<{ alternantByEmail: AlternantEmailCheck }>(res).alternantByEmail
}

export async function deleteAlternant(id: string): Promise<boolean> {
  const res = await pedaGraphqlClient.mutation(DELETE_ALTERNANT, { id })
  return unwrap<{ deleteAlternant: boolean }>(res).deleteAlternant
}

export interface CompanyForm {
  name?: string | null
  address?: string | null
  mentorName?: string | null
  startDate: string
  endDate?: string | null
}

export async function changeAlternantCompany(id: string, company: CompanyForm): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.mutation(CHANGE_COMPANY, { id, company })
  return unwrap<{ changeAlternantCompany: Alternant | null }>(res).changeAlternantCompany
}

export async function removeAlternantCompany(id: string): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.mutation(REMOVE_COMPANY, { id })
  return unwrap<{ removeAlternantCompany: Alternant | null }>(res).removeAlternantCompany
}

export async function linkAlternant(id: string, otherId: string): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.mutation(LINK_ALTERNANT, { id, otherId })
  return unwrap<{ linkAlternant: Alternant | null }>(res).linkAlternant
}

export async function unlinkAlternant(id: string, otherId: string): Promise<Alternant | null> {
  const res = await pedaGraphqlClient.mutation(UNLINK_ALTERNANT, { id, otherId })
  return unwrap<{ unlinkAlternant: Alternant | null }>(res).unlinkAlternant
}

export async function createSequence(alternantId: string, prevueLe: string): Promise<AlternantSequence> {
  const res = await pedaGraphqlClient.mutation(CREATE_SEQUENCE, { alternantId, prevueLe })
  return unwrap<{ createSequence: AlternantSequence }>(res).createSequence
}

export async function updateSequenceContacts(id: string, contacts: Partial<SequenceContacts>): Promise<AlternantSequence | null> {
  const res = await pedaGraphqlClient.mutation(UPDATE_CONTACTS, { id, contacts })
  return unwrap<{ updateSequenceContacts: AlternantSequence | null }>(res).updateSequenceContacts
}

export async function markSequence(id: string, status: SequenceStatus): Promise<AlternantSequence | null> {
  const res = await pedaGraphqlClient.mutation(MARK_SEQUENCE, { id, status })
  return unwrap<{ markSequence: AlternantSequence | null }>(res).markSequence
}

export async function completeSequence(id: string, realiseeLe: string): Promise<AlternantSequence | null> {
  const res = await pedaGraphqlClient.mutation(COMPLETE_SEQUENCE, { id, realiseeLe })
  return unwrap<{ completeSequence: AlternantSequence | null }>(res).completeSequence
}

export async function deleteSequence(id: string): Promise<boolean> {
  const res = await pedaGraphqlClient.mutation(DELETE_SEQUENCE, { id })
  return unwrap<{ deleteSequence: boolean }>(res).deleteSequence
}

export interface CandidateAutofill {
  candidateId: string
  firstName: string
  lastName: string
  email: string
  phone: string
}

/** Auto-remplissage Identité depuis une fiche candidat (recherche par email). */
export async function lookupCandidateByEmail(email: string): Promise<CandidateAutofill | null> {
  const check = await candidateGraphqlClient.query(CHECK_CANDIDATE_EMAIL, { email }, { requestPolicy: 'network-only' })
  if (check.error) throw new Error(check.error.message.replace(/^\[GraphQL\]\s*/, ''))
  const hit = check.data?.candidateByEmail
  if (!hit?.exists || !hit?.id) return null
  const full = await candidateGraphqlClient.query(GET_CANDIDATE_BY_ID, { id: hit.id }, { requestPolicy: 'network-only' })
  if (full.error) throw new Error(full.error.message.replace(/^\[GraphQL\]\s*/, ''))
  const identity = full.data?.candidate?.identity
  if (!identity) return null
  const parts = String(identity.fullName ?? '').trim().split(/\s+/)
  return {
    candidateId: hit.id,
    firstName: parts[0] ?? '',
    lastName: parts.slice(1).join(' '),
    email: identity.email ?? '',
    phone: identity.phone ?? '',
  }
}
