import { Alternant, AlternantSequence } from '../../types/alternant.types';

export function alternantToGql(a: Alternant): object {
    return {
        id: a._id,
        firstName: a.first_name,
        lastName: a.last_name,
        fullName: `${a.first_name} ${a.last_name}`.trim(),
        session: a.session,
        email: a.email ?? null,
        phone: a.phone ?? null,
        candidateId: a.candidate_id ?? null,
        company: a.company
            ? {
                  name: a.company.name ?? null,
                  address: a.company.address ?? null,
                  mentorName: a.company.mentor_name ?? null,
                  startDate: a.company.start_date ? new Date(a.company.start_date).toISOString() : null,
                  endDate: a.company.end_date ? new Date(a.company.end_date).toISOString() : null,
              }
            : null,
        linkedAlternantIds: a.linked_alternant_ids ?? [],
        createdAt: a.created_at ? new Date(a.created_at).toISOString() : null,
        updatedAt: a.updated_at ? new Date(a.updated_at).toISOString() : null,
    };
}

export function sequenceToGql(s: AlternantSequence): object {
    const contacts = s.contacts ?? { mentor: false, alternant: false, formateur: false };
    const contactsDone = [contacts.mentor, contacts.alternant, contacts.formateur].filter(Boolean).length;
    return {
        id: s._id,
        alternantId: s.alternant_id,
        numero: s.numero,
        prevueLe: s.prevue_le ? new Date(s.prevue_le).toISOString() : null,
        status: s.status,
        realiseeLe: s.realisee_le ? new Date(s.realisee_le).toISOString() : null,
        contacts: { ...contacts },
        contactsDone,
        autoGenerated: s.auto_generated,
        createdAt: s.created_at ? new Date(s.created_at).toISOString() : null,
        updatedAt: s.updated_at ? new Date(s.updated_at).toISOString() : null,
    };
}
