export interface AlternantCompany {
  name: string | null
  address: string | null
  mentorName: string | null
  startDate: string | null
  endDate: string | null
}

export interface Alternant {
  id: string
  firstName: string
  lastName: string
  fullName: string
  /** Session du jeune (texte libre — les groupes Sessions arriveront plus tard). */
  session: string
  email: string | null
  phone: string | null
  candidateId: string | null
  company: AlternantCompany | null
  linkedAlternantIds: string[]
  createdAt: string | null
  updatedAt: string | null
}

export type SequenceStatus = 'pending' | 'done' | 'not_done'

export interface SequenceContacts {
  mentor: boolean
  alternant: boolean
  formateur: boolean
}

export interface AlternantSequence {
  id: string
  alternantId: string
  /** Numéro de SA auto-généré. */
  numero: number
  prevueLe: string
  status: SequenceStatus
  realiseeLe: string | null
  contacts: SequenceContacts
  contactsDone: number
  autoGenerated: boolean
  createdAt: string | null
  updatedAt: string | null
}

export interface CreateAlternantInput {
  firstName: string
  lastName: string
  session: string
  email?: string | null
  phone?: string | null
  candidateId?: string | null
  company: {
    name?: string | null
    address?: string | null
    mentorName?: string | null
    startDate: string
    endDate?: string | null
  }
  linkedAlternantIds?: string[]
}
